### PR TITLE
Clicking logo clears form data and returns user to home screen.

### PR DESCRIPTION
**Pull request by keebarber**

### CODE REVIEW

**Comment by BrandonKlotz** [comment]
This is a great feature! Thanks for thinking of it!

**Comment by BrandonKlotz** [comment]
So with this you added an action that returns state to the "initial state" so the Text analyzer component will return the first return in the if/else statement updating the UI to the 'starting screen' ? Let me know if I am reading through the code correctly.

**Comment by HollyJHuber** [comment]
This looks like a nice and proper way to do this. Without React/Redux you would have to reload the page with through js reload function or pointing to the index.html page.

**Comment by keebarber** [comment]
Correct. Our condition for moving to the 2nd screen requires there to be some 'displayResults' from Watson, so the most efficient way of moving back to the main screen seemed to be to clear those results.

**Pull request merged**
